plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.musicapp'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.musicapp'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "1.1"
    }
}

dependencies {
    implementation 'androidx.media:media:1.7.0'
}
